name: Fetch API and Cache

on:
  schedule:
    - cron: '*/5 * * * *'    # 每5分钟运行一次
  workflow_dispatch:         # 允许手动触发

jobs:
  fetch-and-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Fetch API and cache result
        run: python fetch_api.py

      - name: Commit & Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data.json
          git commit -m "Update cache" || echo "No changes to commit"
          git push
